# Generated by Django 2.2.19 on 2021-03-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='certificates',
            new_name='Certificate',
        ),
    ]
