# Generated by Django 2.2.19 on 2021-03-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_auto_20210309_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='levels',
            field=models.IntegerField(default=1, verbose_name='Class Level'),
        ),
    ]
