# Generated by Django 2.2.19 on 2021-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210308_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(choices=[(1, 'Level One'), (2, 'Level Two')]),
        ),
    ]
