# Generated by Django 2.2.19 on 2021-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210309_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(choices=[(2, 'Level Two'), (1, 'Level One')]),
        ),
    ]
