# Generated by Django 2.2.19 on 2021-03-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210311_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(choices=[(2, 'Level Two'), (1, 'Level One')], default=1),
        ),
    ]
