# Generated by Django 2.2.19 on 2021-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='duration',
            field=models.IntegerField(default=2, help_text='Enter number of hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
